# Generated by Django 5.1.7 on 2025-03-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_code", models.CharField(max_length=10)),
                ("local_date", models.DateField()),
                ("close_price", models.IntegerField()),
                ("open_price", models.IntegerField()),
                ("high_price", models.IntegerField()),
                ("low_price", models.IntegerField()),
                ("volume", models.BigIntegerField()),
            ],
        ),
    ]
